model_list:
  - model_name: o3-mini
    litellm_params:
      model: openai/o3-mini                      
      api_key: os.environ/OPENAI_API_KEY
  - model_name: o1-mini
    litellm_params:
      model: openai/o1-mini                      
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-3.5-turbo-instruct
    litellm_params:
      model: text-completion-openai/gpt-3.5-turbo-instruct
      api_key: os.environ/OPENAI_API_KEY