model_list:
  - model_name: o3-mini
    litellm_params:
      model: openai/o3-mini                      
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY